// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfnyivwadljrwqwiibec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbnlpdndhZGxqcndxd2lpYmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzk2ODksImV4cCI6MjA3Mjg1NTY4OX0.KINJAJayN3Pu8Cyc-ZzIRTfCunGOVMDuqkBBiQyiIw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});